dotenv: .env

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
  - smartcontractkit/chainlink-brownie-contracts@0.4.0

compiler:
  solc:
    optimizer:
      enabled: true
      runs: 1000
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"

networks:
  default: development
  development:
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000
    verify: False
  mainnet-fork:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
  rinkeby:
    vrf_coordinator: "0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B"
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    opensea_url: "https://testnets.opensea.io/assets/{}/{}"
    fee: 100000000000000000
    verify: True
    ReneeLaneCollection: "0xd732dEC77Bd7725C55A8325D762904876CE8aDB0"
    ReneeCoins: "0xbfC39dF8CD38Cb19175650AB1B1ABcD18C8edF6b"
  mainnet:
    opensea_url: "https://opensea.io/assets/{}/{}"
    verify: true

wallets:
  from_key: ${PRIVATE_KEY}

pinata:
  api: ${PINATA_API_KEY}
  secret: ${PINATA_SECRET_KEY}
  url: "https://api.pinata.cloud"
  pinning_endpoint: "/pinning/pinFileToIPFS"

reports:
  exclude_paths: null
  exclude_contracts: null
  only_include_project: true
